#!/bin/bash

ARG_INPUT_VIDEO_FILE_NAME=$1;
ARG_OUTPUT_GIF_FILE_NAME=$2;
ARG_OUTPUT_FRAME_RATE=$3;

DEFAULT_OUTPUT_FILE_NAME="out.gif";
DEFAULT_OUTPUT_FRAME_RATE=5;

if [ -x "$(command -v ffmpeg)" ]
  then
  
    if [ -z "$ARG_INPUT_VIDEO_FILE_NAME" ]
      then
        echo "ERROR! No file video input supplied as 1st parameter.";
        echo "Usage examples:";
        echo "mp4-to-gif.sh video.mp4 video.gif";
        echo "mp4-to-gif.sh video.mp4 video.gif 10";
        exit 1;
      else
        COMMAND_INPUT_VIDEO_FILE_NAME=$ARG_INPUT_VIDEO_FILE_NAME;
    fi
    
    if [ -z "$ARG_OUTPUT_GIF_FILE_NAME" ]
      then
        COMMAND_OUTPUT_GIF_FILE_NAME=$DEFAULT_OUTPUT_FILE_NAME;
        echo "WARNING! No output file name supplied as 2nd parameter. Default output name: $COMMAND_OUTPUT_GIF_FILE_NAME";
      else
        COMMAND_OUTPUT_GIF_FILE_NAME=$ARG_OUTPUT_GIF_FILE_NAME;
    fi
    
    if [ -z "$ARG_OUTPUT_FRAME_RATE" ]
      then
        COMMAND_OUTPUT_FRAME_RATE=$DEFAULT_OUTPUT_FRAME_RATE;
        echo "WARNING! No frame rate supplied as 3rd parameter. Value set to: $COMMAND_OUTPUT_FRAME_RATE";
      else
        COMMAND_OUTPUT_FRAME_RATE=$ARG_OUTPUT_FRAME_RATE;
    fi
    
    # Execute video conversion to gif
    ffmpeg -i $COMMAND_INPUT_VIDEO_FILE_NAME -r $COMMAND_OUTPUT_FRAME_RATE -pix_fmt rgb24 $COMMAND_OUTPUT_GIF_FILE_NAME
    
  else
    echo "ERROR! ffmpeg must be installed and in PATH.";
fi




